apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-z1ec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-z1ec
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-z1ec
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-z1ec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-z1ec
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-koyu-tenant/rhtap-demo-app/hacbs-test-project-z1ec@sha256:b64b48079d73af1e6ff82d2711fd6e09bd814d1d320d47eca7aa9262a2c677c5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
